Run tests as part of pre-commit hook

diff --git a/code-analysis/pre-commit b/code-analysis/pre-commit
--- a/code-analysis/pre-commit
+++ b/code-analysis/pre-commit
@@ -3,11 +3,22 @@
 echo "Running pre-commit hook"
 
 ./gradlew checkstyleMain
-
-if [ $? -eq 0 ]; then
-  ./gradlew pmdMain
-  exit $?
-else
-  echo "Pre-commit hook failed"
+if [ $? -ne 0 ]; then
+  echo "Checkstyle violations found, fix before commit"
   exit 1
 fi
+
+./gradlew pmdMain
+if [ $? -ne 0 ]; then
+  echo "PMD violations found, fix before commit"
+  exit 1
+fi
+
+./gradlew test
+if [ $? -ne 0 ]; then
+  echo "Tests failed, fix before commit"
+  exit 1
+fi
+
+echo "Pre-commit hook passed"
+exit 0
